apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: minecraft-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minecraft-deployment
  minReplicas: 1           # 최소 파드 수
  maxReplicas: 5           # 최대 파드 수
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # CPU 평균 사용률이 50%를 넘으면 파드 추가
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75  # 메모리 평균 사용률이 75%를 넘으면 파드 추가
